version: '3.7'

services:
        
        wordpress:
                image: wordpress:php8.0-apache
                ports:
                        - 8080:80
                environment:
                        WORDPRESS_DB_HOST: mysql
                        WORDPRESS_DB_USER: root
                        WORDPRESS_DB_PASSWORD: root
                        WORDPRESS_DB_NAME: wordpress
                links:
                        - mysql:mysql

        mysql:
                image: mysql:5.7
                command: --default-authentication-plugin=mysql_native_password
                volumes:
                        - ~/docker/mysql-data:/var/lib/mysql 
                environment:
                        MYSQL_ROOT_PASSWORD: root 
                        MYSQL_DATABASE: wordpress